backend:
  name: git-gateway
  branch: main # Agar aapki repository ka main branch "master" hai toh yahan master likhein

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "All Games Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Game Title", name: "title", widget: "string" }
      - { label: "Game Icon Image URL", name: "icon", widget: "string" }
      - { label: "APK Download Link", name: "download_url", widget: "string" }
      - { label: "APK Size", name: "size", widget: "string", default: "40.5 MB" }
      - { label: "Game Description", name: "body", widget: "markdown" }
